---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Code* resources'

Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: "DummyGoApp"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        # DO NOT DO THIS IN PRODUCTION!!!
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DummyGoPipeline
      # The role is already created.
      # Do the same here:
      # https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-create-service-role-console.html
      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/AWS-CodePipeline-Service"
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: artifact-store-us-east-1
        - Region: us-west-1
          ArtifactStore:
            Type: S3
            Location: artifact-store-us-west-1
        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: artifact-store-us-west-2
      Stages:
        -
          Name: PollSCM
          Actions:
            -
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: !GetAtt CodeCommitRepo.Name
                BranchName: main
              OutputArtifacts:
                -
                  Name: SourceCode
        -
          Name: Build
          Actions:
            -
              Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: Deployment
        -
          Name: Deploy
          Actions:
            -
              Name: USE1
              Region: us-east-1
              InputArtifacts:
                - Name: Deployment
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: DummyGoApp
                DeploymentGroupName: DummyGoAppGroup
            -
              Name: USW1
              Region: us-west-1
              InputArtifacts:
                - Name: Deployment
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: DummyGoApp
                DeploymentGroupName: DummyGoAppGroup
            -
              Name: USW2
              Region: us-west-2
              InputArtifacts:
                - Name: Deployment
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: DummyGoApp
                DeploymentGroupName: DummyGoAppGroup
